<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://webservices.www.ecubicle.net/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://schemas.xmlsoap.org/wsdl/" targetNamespace="http://webservices.www.ecubicle.net/" name="GsearchRssSoap">
	<import namespace="http://www.ecubicle.net/webservices" location="imported.wsdl"/>
	<binding xmlns:ns1="http://www.ecubicle.net/webservices" name="gsearch_rssSoap" type="ns1:gsearch_rssSoap">
		<soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
		<operation name="GetSearchResults">
			<soap:operation soapAction="http://www.ecubicle.net/webservices/GetSearchResults" style="document"/>
			<input>
				<soap:body use="literal"/>
			</input>
			<output>
				<soap:body use="literal"/>
			</output>
		</operation>
	</binding>
	<service name="gsearch_rss">
		<port name="gsearch_rssSoap" binding="tns:gsearch_rssSoap">
			<soap:address location="http://www.ecubicle.net/gsearch_rss.asmx"/>
		</port>
	</service>
</definitions>
<!-- <?xml version="1.0" encoding="utf-8" standalone="yes" ?> <soap:Envelope 
	xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xmlns:xsd="http://www.w3.org/2001/XMLSchema" > <soap:Body> <GetSearchResults 
	xmlns = "http://webservices.www.ecubicle.net/"> <searchPage></searchPage> 
	<gQuery>JBoss Web Services</gQuery> <numOfResults></numOfResults> </GetSearchResults> 
	</soap:Body> </soap:Envelope>
	 -->