name: Build and Test

on:
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ${{ matrix.os }} # compiles and test on Ubuntu

    strategy:
      matrix:
        os: [ubuntu-latest]
        java: ["11"]
      fail-fast: false

    steps:
    - name: Checkout PR branch
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}

    - name: Checkout JBoss Tools Build CI
      uses: actions/checkout@v2
      with:
        repository: jbosstools/jbosstools-build-ci
        path: build-ci
    - name: Setup Java ${{ matrix.java }}
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
        java-package: jdk # (jre, jdk, or jdk+fx) - defaults to jdk
        architecture: x64
    - name: Build/Compile and run unit tests
      uses: GabrielBB/xvfb-action@v1
      with:
        run: mvn clean verify -U -fae -B --settings build-ci/maven-settings.xml -DskipITests=true -Dmaven.test.error.ignore=true -Dmaven.test.failure.ignore=true
    - name: Archiving test artifacts
      uses: actions/upload-artifact@v2
      with: 
        name: ${{ matrix.os }}-test-reports
        path: |
          *tests/*/target/surefire-reports/
          */*tests/*/target/surefire-reports/
          **/*.log
